= API documentation for iZettle Product Library


[[_overview]]
== Overview
A product library is a representation of all the items that can be displayed, put in a shopping cart and sold to a customer. Items may be either producs or discounts.

A product is a syntethic construct, wrapping one or more variants (which is the actual item being sold). Variants expresses different variations of properties such as for example price, size or color.

A discount will reduce the total amount charged in a shopping cart. It can be used per item line, or on the whole cart. It may reduce the affected amount by a percentage, or by a fixed amount.

Modifiers is defined as a separate entity, and can be referenced from a product. This will enable the product to have different "modifiers" that can alter it's final price. For example different dressings (modifiers) added on top of a salad (product)

Together, the above types of entities makes up a complete library. The library can be fetched as a whole through the library endpoint, where each consecutive change applied to the library is available. Once the full library is retrieved, only later events needs to be fetched to keep the client up to date with the server.

All path patterns "/organizations/{organizationUuid}/" can be replaced by "/organizations/self/" for convenience as all endpoints are for authorized users.


=== Version information
[%hardbreaks]
_Version_ : v1.0


=== Contact information
[%hardbreaks]
_Contact_ : iZettle Storefront team
_Contact Email_ : storefront@izettle.com


=== URI scheme
[%hardbreaks]
_BasePath_ : /
_Schemes_ : HTTPS, HTTP


=== Tags

* discounts
* export
* library
* modifiersets
* products


=== Consumes

* `application/json`


=== Produces

* `application/json`



