== Zettle API Changelog
.**May 3, 2021** `Pusher API`
[%collapsible]
====
**Pusher API documentation Improvements**

The improvements include the following:

- Improved API reference document.
- Added the list of currently supported events in the API reference document.
- Added the user guides and troubleshooting documents.
====

.**Oct 28, 2020** `Editorial changes`
[%collapsible]
====
**Applied a Beta label on any mention of API documentation**

The current state of the API documentation leaves plenty of room for improvement.

To be transparent and set expectations right, we've applied a Beta label on any mention of the API documentation.

In the meantime, we will work hard to improve the Zettle Developer Platform. An example of the ongoing work is to improve the API documentation.
====

.**Sep 21, 2020** `Finance` `Purchase` `Product library` `Image`
[%collapsible]
====
Updated documentation for Finance, Purchase, Product Library, and Image APIs.

**Finance API**

- Removed transaction type `SUBSCRIPTION_CHARGE`, since it was incorrectly added to the documentation.
- Clarified that `VOUCHER_ACTIVATION` does not appear on the `LIQUID` account.
- Marked the `TELL_FRIEND` transaction type as *deprecated*. This transaction type was removed in late 2018, but may show up in transactions prior to that.

**Purchase API**

- Removed the `CUSTOM` payment type. This payment type does not exist anymore and has not been in use.

**Product Library API**

- Updated the example request under the "Create product" section to reflect the new `category` and `variantOptionDefinitions` fields.

The `category` field replaces the old `categories` field. Now, a product may only have one category assigned to it. To create a new product category, simply provide a new UUID (v1) value for the `category.uuid` field when creating or updating a product, for example:

[source,json]
--
{
    "category": {
        "uuid": "1ee20a82-fb8a-11ea-adc1-0242ac120002",
        "name": "New Category"
    }
}
--

- The `imageLookupKeys` field has been deprecated in favour of `presentation.imageUrl`.
- Added an example request under the "Update product" section.
- Added descriptions about Product Categories.

**Image API**

- Replaced usage of `imageLookupKey` with `imageUrls`. The `imageLookupKey` has been deprecated. Instead, the fully qualified URLs should be used.
====